'use client'

import { useState } from 'react'
import { useLocale } from '@/locales'
import type { JobInsightContent, InsightVerdict, InsightRecommendation } from '@/app/db/schema'
import { card, cardHeader, cardBody, sectionLabel } from '@/app/lib/styles'

export const VERDICT_CONFIG: Record<InsightVerdict, { label: string; color: string; bg: string }> = {
  strong_fit:  { label: 'Strong Fit',  color: 'text-emerald-700 dark:text-emerald-400', bg: 'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800' },
  good_fit:    { label: 'Good Fit',    color: 'text-blue-700 dark:text-blue-400',       bg: 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800' },
  stretch:     { label: 'Stretch',     color: 'text-amber-700 dark:text-amber-400',     bg: 'bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800' },
  low_fit:     { label: 'Low Fit',     color: 'text-red-700 dark:text-red-400',         bg: 'bg-red-50 dark:bg-red-900/20 border-red-200 dark:border-red-800' },
}

export const RECOMMENDATION_CONFIG: Record<InsightRecommendation, { label: string; icon: string }> = {
  strong_apply:         { label: 'Strong fit — apply now',                      icon: '🚀' },
  apply_with_tailoring: { label: 'Good fit — apply with resume updates',        icon: '✏️' },
  stretch:              { label: 'Stretch role — apply if genuinely interested', icon: '🎯' },
  low_fit:              { label: 'Low fit — consider your priorities',           icon: '⚠️' },
}

export function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className={`${card} overflow-hidden`}>
      <div className={cardHeader}>
        <h3 className={sectionLabel}>{title}</h3>
      </div>
      <div className={cardBody}>{children}</div>
    </div>
  )
}

export function BulletList({ items, color = 'text-zinc-600 dark:text-zinc-300' }: { items: string[]; color?: string }) {
  if (!items?.length) return <p className="text-sm text-zinc-400">—</p>
  return (
    <ul className="space-y-1.5">
      {items.map((item, i) => (
        <li key={i} className={`flex gap-2 text-sm ${color}`}>
          <span className="text-zinc-300 dark:text-zinc-600 shrink-0 mt-0.5">•</span>
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}

export function exportToMarkdown(content: JobInsightContent, company: string, role: string): string {
  const rec = RECOMMENDATION_CONFIG[content.applyDecision.recommendation]
  const verdict = VERDICT_CONFIG[content.matchAnalysis.verdict]
  return `# Job Insight: ${role} @ ${company}

## Role Profile

| | |
|---|---|
| **Type** | ${content.roleProfile.type} |
| **Seniority** | ${content.roleProfile.seniority} |
| **Orientation** | ${content.roleProfile.orientation} |
| **Company Context** | ${content.roleProfile.companyContext} |

${content.roleProfile.summary}

---

## Match Analysis

**Verdict:** ${verdict.label}

**${content.matchAnalysis.headline}**

### Strong Signals
${content.matchAnalysis.strongSignals.map(s => `- ${s}`).join('\n')}

### Main Risks
${content.matchAnalysis.mainRisks.map(s => `- ${s}`).join('\n')}

---

## Requirements Breakdown

### Must-Have
${content.requirements.mustHave.map(s => `- ${s}`).join('\n')}

### Nice-to-Have
${content.requirements.niceToHave.map(s => `- ${s}`).join('\n')}

### Hidden Expectations
${content.requirements.hiddenExpectations.map(s => `- ${s}`).join('\n')}

### Noise (can ignore)
${content.requirements.noise.map(s => `- ${s}`).join('\n')}

---

## Application Strategy

### Best Emphasis
${content.strategy.bestEmphasis.map(s => `- ${s}`).join('\n')}

### De-emphasise
${content.strategy.deEmphasize.map(s => `- ${s}`).join('\n')}

### Core Narrative
${content.strategy.bestStory}

---

## Apply Decision

${rec.icon} **${rec.label}**

${content.applyDecision.rationale}

### Action Items
${content.applyDecision.actionItems.map(s => `- [ ] ${s}`).join('\n')}

---

## Interview Preparation

### Why This Company
${content.interviewPrep.whyCompany.map(s => `- ${s}`).join('\n')}

### Why This Role
${content.interviewPrep.whyRole.map(s => `- ${s}`).join('\n')}

### Likely Technical Topics
${content.interviewPrep.likelyTechnical.map(s => `- ${s}`).join('\n')}

### Behavioural Themes
${content.interviewPrep.behavioralThemes.map(s => `- ${s}`).join('\n')}

### Objections to Handle
${content.interviewPrep.objectionsToHandle.map(o => `**Q: ${o.objection}**\n${o.response}`).join('\n\n')}

---

## Application Materials

### Resume Headline
${content.applicationMaterials.resumeHeadline}

### Short Application Statement
${content.applicationMaterials.shortStatement}

### Recruiter / Outreach Message
${content.applicationMaterials.recruiterMessage}

---
*Generated by ApplyDay*
`
}

function buildResumeEditPrompt(content: JobInsightContent, company?: string, jobTitle?: string): string {
  const role = [jobTitle, company].filter(Boolean).join(' at ') || content.roleProfile.type
  const ul = (items: string[]) => items.map(s => `- ${s}`).join('\n')
  return `You are helping me tailor my resume for a specific job application.

**Target Role:** ${role}
**Seniority:** ${content.roleProfile.seniority}
**Company Context:** ${content.roleProfile.companyContext}

---

## Must-Have Requirements
${ul(content.requirements.mustHave)}

## Nice-to-Have
${ul(content.requirements.niceToHave)}

## Key Gaps to Address
${ul(content.matchAnalysis.mainRisks)}

---

## What to Emphasize
${ul(content.strategy.bestEmphasis)}

## What to De-emphasize or Remove
${ul(content.strategy.deEmphasize)}

## Core Narrative to Build
${content.strategy.bestStory}

## Target Resume Headline
${content.applicationMaterials.resumeHeadline}

---

Please review my resume below and suggest specific edits to:
1. Address the identified gaps — be direct if a gap cannot realistically be bridged
2. Restructure or reword bullet points to highlight the must-have requirements
3. Adjust the ordering and framing to lead with the strongest signals
4. Rewrite my summary/headline to match the target headline above

[PASTE YOUR RESUME HERE]`
}

interface Props {
  content: JobInsightContent
  company?: string
  jobTitle?: string
}

export default function JobInsightView({ content, company, jobTitle }: Props) {
  const { t } = useLocale()
  const v = VERDICT_CONFIG[content.matchAnalysis.verdict]
  const [copied, setCopied] = useState(false)

  const handleCopyPrompt = async () => {
    await navigator.clipboard.writeText(buildResumeEditPrompt(content, company, jobTitle))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="space-y-4">
      {/* Role Profile */}
      <Section title={t('jobInsightRoleProfile')}>
        <div className="grid sm:grid-cols-2 gap-3 mb-3">
          {[
            { label: 'Type',            value: content.roleProfile.type },
            { label: 'Seniority',       value: content.roleProfile.seniority },
            { label: 'Orientation',     value: content.roleProfile.orientation },
            { label: 'Company Context', value: content.roleProfile.companyContext },
          ].map(({ label, value }) => (
            <div key={label} className="rounded-lg bg-zinc-50 dark:bg-zinc-800 px-3 py-2">
              <p className="text-[10px] font-semibold text-zinc-400 uppercase tracking-wider">{label}</p>
              <p className="text-sm text-zinc-800 dark:text-zinc-200 mt-0.5">{value}</p>
            </div>
          ))}
        </div>
        <p className="text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">{content.roleProfile.summary}</p>
      </Section>

      {/* Match Analysis */}
      <Section title={t('jobInsightMatchAnalysis')}>
        <div className={`rounded-lg border px-4 py-3 mb-4 ${v.bg}`}>
          <p className={`text-sm font-bold ${v.color}`}>{v.label}</p>
          <p className={`text-sm mt-0.5 ${v.color}`}>{content.matchAnalysis.headline}</p>
        </div>
        <div className="grid sm:grid-cols-2 gap-4">
          <div>
            <p className="text-xs font-semibold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider mb-2">{t('jobInsightStrongSignals')}</p>
            <BulletList items={content.matchAnalysis.strongSignals} color="text-zinc-600 dark:text-zinc-300" />
          </div>
          <div>
            <p className="text-xs font-semibold text-red-500 dark:text-red-400 uppercase tracking-wider mb-2">{t('jobInsightMainRisks')}</p>
            <BulletList items={content.matchAnalysis.mainRisks} color="text-zinc-600 dark:text-zinc-300" />
          </div>
        </div>
      </Section>

      {/* Requirements */}
      <Section title={t('jobInsightRequirements')}>
        <div className="grid sm:grid-cols-2 gap-4">
          <div>
            <p className="text-xs font-semibold text-red-500 dark:text-red-400 uppercase tracking-wider mb-2">{t('jobInsightMustHave')}</p>
            <BulletList items={content.requirements.mustHave} />
          </div>
          <div>
            <p className="text-xs font-semibold text-blue-500 dark:text-blue-400 uppercase tracking-wider mb-2">{t('jobInsightNiceToHave')}</p>
            <BulletList items={content.requirements.niceToHave} />
          </div>
          <div>
            <p className="text-xs font-semibold text-amber-500 dark:text-amber-400 uppercase tracking-wider mb-2">{t('jobInsightHidden')}</p>
            <BulletList items={content.requirements.hiddenExpectations} />
          </div>
          <div>
            <p className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">{t('jobInsightNoise')}</p>
            <BulletList items={content.requirements.noise} color="text-zinc-400 dark:text-zinc-500" />
          </div>
        </div>
      </Section>

      {/* Strategy */}
      <Section title={t('jobInsightStrategy')}>
        <div className="grid sm:grid-cols-2 gap-4 mb-4">
          <div>
            <p className="text-xs font-semibold text-indigo-500 dark:text-indigo-400 uppercase tracking-wider mb-2">{t('jobInsightEmphasize')}</p>
            <BulletList items={content.strategy.bestEmphasis} />
          </div>
          <div>
            <p className="text-xs font-semibold text-zinc-400 uppercase tracking-wider mb-2">{t('jobInsightDeEmphasize')}</p>
            <BulletList items={content.strategy.deEmphasize} color="text-zinc-400 dark:text-zinc-500" />
          </div>
        </div>
        <div className="rounded-lg bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-100 dark:border-indigo-800 px-4 py-3">
          <p className="text-xs font-semibold text-indigo-500 dark:text-indigo-400 uppercase tracking-wider mb-1">{t('jobInsightBestStory')}</p>
          <p className="text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed italic">&ldquo;{content.strategy.bestStory}&rdquo;</p>
        </div>
      </Section>

      {/* Apply Decision */}
      <Section title={t('jobInsightApplyDecision')}>
        {(() => {
          const rec = RECOMMENDATION_CONFIG[content.applyDecision.recommendation]
          const vv = VERDICT_CONFIG[content.matchAnalysis.verdict]
          return (
            <>
              <div className={`rounded-lg border px-4 py-3 mb-4 ${vv.bg}`}>
                <p className={`text-base font-bold ${vv.color}`}>{rec.icon} {rec.label}</p>
              </div>
              <p className="text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed mb-4">{content.applyDecision.rationale}</p>
              <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">{t('jobInsightActionItems')}</p>
              <ul className="space-y-1.5">
                {content.applyDecision.actionItems.map((item, i) => (
                  <li key={i} className="flex gap-2 text-sm text-zinc-600 dark:text-zinc-300">
                    <span className="text-indigo-400 shrink-0 mt-0.5">☐</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </>
          )
        })()}
      </Section>

      {/* Interview Prep */}
      <Section title={t('jobInsightInterviewPrep')}>
        <div className="grid sm:grid-cols-2 gap-4 mb-4">
          <div>
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">{t('jobInsightWhyCompany')}</p>
            <BulletList items={content.interviewPrep.whyCompany} />
          </div>
          <div>
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">{t('jobInsightWhyRole')}</p>
            <BulletList items={content.interviewPrep.whyRole} />
          </div>
          <div>
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">{t('jobInsightTechnical')}</p>
            <BulletList items={content.interviewPrep.likelyTechnical} />
          </div>
          <div>
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">{t('jobInsightBehavioral')}</p>
            <BulletList items={content.interviewPrep.behavioralThemes} />
          </div>
        </div>
        {content.interviewPrep.objectionsToHandle.length > 0 && (
          <div className="space-y-3">
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider">{t('jobInsightObjections')}</p>
            {content.interviewPrep.objectionsToHandle.map((o, i) => (
              <div key={i} className="rounded-lg bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 px-4 py-3 space-y-1.5">
                <p className="text-xs font-semibold text-zinc-600 dark:text-zinc-300">Q: {o.objection}</p>
                <p className="text-sm text-zinc-500 dark:text-zinc-400">{o.response}</p>
              </div>
            ))}
          </div>
        )}
      </Section>

      {/* Application Materials */}
      <Section title={t('jobInsightMaterials')}>
        <div className="space-y-4">
          <div>
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-1.5">{t('jobInsightResumeHeadline')}</p>
            <div className="rounded-lg bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 px-4 py-2.5 text-sm text-zinc-800 dark:text-zinc-200 font-medium">
              {content.applicationMaterials.resumeHeadline}
            </div>
          </div>
          <div>
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-1.5">{t('jobInsightShortStatement')}</p>
            <div className="rounded-lg bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 px-4 py-3 text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed whitespace-pre-wrap">
              {content.applicationMaterials.shortStatement}
            </div>
          </div>
          <div>
            <p className="text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-1.5">{t('jobInsightRecruiterMsg')}</p>
            <div className="rounded-lg bg-zinc-50 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 px-4 py-3 text-sm text-zinc-700 dark:text-zinc-300 leading-relaxed whitespace-pre-wrap">
              {content.applicationMaterials.recruiterMessage}
            </div>
          </div>
        </div>
      </Section>

      {/* Resume Changes */}
      {content.resumeEdits && (
        <Section title={t('resumeEditsTitle')}>
          <div className="grid sm:grid-cols-2 gap-4">
            <div>
              <p className="text-xs font-semibold text-red-500 dark:text-red-400 uppercase tracking-wider mb-2.5 flex items-center gap-1.5">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
                {t('resumeEditsRemove')}
              </p>
              <ul className="space-y-2">
                {content.resumeEdits.remove.map((item, i) => {
                  const [what, why] = item.split(/ — reason: | — /i)
                  return (
                    <li key={i} className="rounded-lg bg-red-50 dark:bg-red-900/10 border border-red-100 dark:border-red-900/30 px-3 py-2">
                      <p className="text-sm font-medium text-red-700 dark:text-red-300">{what?.trim()}</p>
                      {why && <p className="text-xs text-red-500 dark:text-red-400 mt-0.5">{why.trim()}</p>}
                    </li>
                  )
                })}
              </ul>
            </div>
            <div>
              <p className="text-xs font-semibold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider mb-2.5 flex items-center gap-1.5">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M12 4v16m8-8H4" />
                </svg>
                {t('resumeEditsAdd')}
              </p>
              <ul className="space-y-2">
                {content.resumeEdits.add.map((item, i) => {
                  const [what, maps] = item.split(/ — maps to: | — /i)
                  return (
                    <li key={i} className="rounded-lg bg-emerald-50 dark:bg-emerald-900/10 border border-emerald-100 dark:border-emerald-900/30 px-3 py-2">
                      <p className="text-sm font-medium text-emerald-700 dark:text-emerald-300">{what?.trim()}</p>
                      {maps && <p className="text-xs text-emerald-600 dark:text-emerald-500 mt-0.5">{maps.trim()}</p>}
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>
        </Section>
      )}

      {/* Resume Edit Prompt */}
      <Section title={t('resumeEditPromptTitle')}>
        <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-3">{t('resumeEditPromptDesc')}</p>
        <div className="relative">
          <pre className="text-xs text-zinc-700 dark:text-zinc-300 bg-zinc-50 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-700 rounded-lg px-4 py-3 overflow-auto max-h-64 whitespace-pre-wrap leading-relaxed font-mono">
            {buildResumeEditPrompt(content, company, jobTitle)}
          </pre>
          <button
            onClick={handleCopyPrompt}
            className="absolute top-2 right-2 flex items-center gap-1.5 px-2.5 py-1.5 rounded-md text-xs font-semibold bg-white dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-600 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-700 transition-colors shadow-sm"
          >
            {copied ? (
              <>
                <svg className="w-3.5 h-3.5 text-emerald-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                </svg>
                {t('copied')}
              </>
            ) : (
              <>
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                </svg>
                {t('copy')}
              </>
            )}
          </button>
        </div>
      </Section>
    </div>
  )
}
